server:
  port: 50000

backbase:
  my_secret: ${MY_SECRET:my yaml secret}

spring:
  datasource:
    url: jdbc:h2:mem:urldb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false

scheduled:
  task:
    delete-time: 1800000